const { PlayableExtractorPlugin, Playlist, Song, DisTubeError } = require("distube");
const { spawn } = require("child_process");
const path = require("path");
const fs = require("fs");
const { metadataCache, streamUrlCache, singleFlight } = require("./Cache");

function resolveBinaryPath() {
  const localBinary = path.join(
    __dirname,
    "..",
    "node_modules",
    "@distube",
    "yt-dlp",
    "bin",
    process.platform === "win32" ? "yt-dlp.exe" : "yt-dlp"
  );
  if (fs.existsSync(localBinary)) {
    return localBinary;
  }
  return "yt-dlp";
}

function cleanYoutubeUrl(rawUrl) {
  if (typeof rawUrl !== "string") return rawUrl;
  try {
    const parsed = new URL(rawUrl);
    // If it is a YouTube video URL with Mix/Radio or autogenerated playlist parameters attached
    if (parsed.pathname === "/watch" && parsed.searchParams.has("v")) {
      const list = parsed.searchParams.get("list");
      if (
        !list ||
        list.startsWith("RD") ||
        list.startsWith("LL") ||
        list.startsWith("FL") ||
        parsed.searchParams.get("start_radio") === "1"
      ) {
        parsed.searchParams.delete("list");
        parsed.searchParams.delete("start_radio");
        parsed.searchParams.delete("index");
        return parsed.toString();
      }
    }
    return rawUrl;
  } catch {
    return rawUrl;
  }
}

function fetchFastStreamUrl(rawUrl) {
  const url = cleanYoutubeUrl(rawUrl);
  const cached = streamUrlCache.get(url) || streamUrlCache.get(rawUrl);
  if (cached) {
    return Promise.resolve(cached);
  }

  return singleFlight.do(`stream:${url}`, () => {
    const binary = resolveBinaryPath();
    const rootCookies = path.join(__dirname, "..", "cookies.txt");
    const cookieFlags = fs.existsSync(rootCookies) ? ["--cookies", rootCookies] : [];

    const flags = [
      "-g",
      "--no-warnings",
      "--no-check-certificates",
      "--no-playlist",
      "-f",
      "ba/ba*",
      "--extractor-args",
      "youtube:player_client=android;player_skip=webpage,configs",
      ...cookieFlags,
      url,
    ];

    return new Promise((resolve, reject) => {
      const startTime = Date.now();
      const proc = spawn(binary, flags);
      let stdout = "";
      let stderr = "";

      proc.stdout.on("data", (chunk) => {
        stdout += chunk;
      });
      proc.stderr.on("data", (chunk) => {
        stderr += chunk;
      });

      proc.on("close", (code) => {
        const streamUrl = stdout.trim().split("\n")[0]?.trim();
        if (code === 0 && streamUrl && streamUrl.startsWith("http")) {
          streamUrlCache.set(url, streamUrl);
          streamUrlCache.set(rawUrl, streamUrl);
          resolve(streamUrl);
        } else {
          console.error(`[yt-dlp fast stream error] Code: ${code}, Stderr: ${stderr || stdout}`);
          reject(new Error(stderr || stdout || `yt-dlp exited with code ${code}`));
        }
      });

      proc.on("error", (err) => {
        console.error(`[yt-dlp spawn error]:`, err);
        reject(err);
      });
    });
  });
}

function runYtDlpJson(rawUrl, extraFlags = []) {
  const url = cleanYoutubeUrl(rawUrl);
  const binary = resolveBinaryPath();
  
  const isExplicitPlaylist =
    !url.includes("watch?") &&
    (url.includes("/playlist") || /[?&]list=PL/i.test(url));
  const playlistFlag = isExplicitPlaylist ? ["--yes-playlist"] : ["--no-playlist"];

  const flags = [
    "-j",
    "--no-warnings",
    "--prefer-free-formats",
    "--skip-download",
    "--simulate",
    "--extractor-args",
    "youtube:player_client=android",
    ...playlistFlag,
    ...extraFlags,
    url,
  ];

  return new Promise((resolve, reject) => {
    const proc = spawn(binary, flags);
    let stdout = "";
    let stderr = "";

    proc.stdout.on("data", (chunk) => {
      stdout += chunk;
    });
    proc.stderr.on("data", (chunk) => {
      stderr += chunk;
    });

    proc.on("close", (code) => {
      if (code === 0) {
        try {
          const lines = stdout
            .trim()
            .split("\n")
            .map((l) => l.trim())
            .filter((l) => l.startsWith("{"));

          if (lines.length === 0) {
            return reject(new Error("No JSON metadata found in yt-dlp output"));
          }
          if (lines.length === 1) {
            const parsed = JSON.parse(lines[0]);
            resolve(parsed);
          } else {
            const entries = lines.map((l) => JSON.parse(l));
            resolve({
              _type: "playlist",
              extractor: entries[0]?.extractor || "youtube",
              id: entries[0]?.playlist_id || entries[0]?.playlist || "playlist",
              title: entries[0]?.playlist_title || "YouTube Playlist",
              webpage_url: url,
              entries,
            });
          }
        } catch (err) {
          console.error(`[yt-dlp JSON parse error]:`, err);
          reject(err);
        }
      } else {
        console.error(`[yt-dlp JSON exit error] Code: ${code}, Stderr: ${stderr || stdout}`);
        reject(new Error(stderr || stdout || `yt-dlp exited with code ${code}`));
      }
    });

    proc.on("error", (err) => {
      console.error(`[yt-dlp spawn error]:`, err);
      reject(err);
    });
  });
}

class CustomYtDlpSong extends Song {
  constructor(plugin, info, options = {}) {
    super(
      {
        plugin,
        source: info.extractor || "youtube",
        playFromSource: true,
        id: info.id || info.videoId,
        name: info.title || info.fulltitle,
        url: info.webpage_url || info.original_url || info.url || `https://youtu.be/${info.id || info.videoId}`,
        isLive: Boolean(info.is_live || info.live),
        thumbnail: info.thumbnail || info.thumbnails?.[0]?.url || (info.image ? info.image : undefined),
        duration: info.is_live ? 0 : info.duration || info.seconds || 0,
        uploader: {
          name: info.uploader || info.author?.name || "YouTube",
          url: info.uploader_url || info.author?.url || "",
        },
        views: info.view_count || info.views || 0,
        likes: info.like_count || 0,
        dislikes: info.dislike_count || 0,
        reposts: info.repost_count || 0,
        ageRestricted: Boolean(info.age_limit && info.age_limit >= 18),
      },
      options
    );
  }
}

class CustomYtDlpPlugin extends PlayableExtractorPlugin {
  constructor(options = {}) {
    super();
    this.options = options;
  }

  validate() {
    return true;
  }

  _getCookieFlags() {
    const rootCookies = path.join(__dirname, "..", "cookies.txt");
    if (fs.existsSync(rootCookies)) {
      return ["--cookies", rootCookies];
    }
    return [];
  }

  async resolve(url, options = {}) {
    const cleanUrl = cleanYoutubeUrl(url);
    const cachedInfo = metadataCache.get(cleanUrl) || metadataCache.get(url);
    if (cachedInfo) {
      return new CustomYtDlpSong(this, cachedInfo, options);
    }

    const extraFlags = [...this._getCookieFlags()];
    const info = await runYtDlpJson(cleanUrl, extraFlags).catch((err) => {
      console.error(`[YtDlpPlugin Resolve Error]:`, err.message || err);
      throw new DisTubeError("YTDLP_ERROR", `${err.message || err}`);
    });

    if (Array.isArray(info.entries)) {
      if (info.entries.length === 0) {
        throw new DisTubeError("YTDLP_ERROR", "The playlist is empty");
      }
      return new Playlist(
        {
          source: info.extractor || "youtube",
          songs: info.entries.map((i) => new CustomYtDlpSong(this, i, options)),
          id: info.id?.toString() || "",
          name: info.title,
          url: info.webpage_url || cleanUrl,
          thumbnail: info.thumbnails?.[0]?.url,
        },
        options
      );
    }

    metadataCache.set(cleanUrl, info);
    metadataCache.set(url, info);
    return new CustomYtDlpSong(this, info, options);
  }

  async getStreamURL(song) {
    if (!song.url) {
      throw new DisTubeError(
        "YTDLP_PLUGIN_INVALID_SONG",
        "Cannot get stream url from invalid song."
      );
    }
    const streamUrl = await fetchFastStreamUrl(song.url).catch((err) => {
      console.error(`[YtDlpPlugin Stream Error]:`, err.message || err);
      throw new DisTubeError("YTDLP_ERROR", `${err.message || err}`);
    });

    return streamUrl;
  }

  getRelatedSongs() {
    return [];
  }
}

module.exports = {
  CustomYtDlpPlugin,
  CustomYtDlpSong,
  fetchFastStreamUrl,
  cleanYoutubeUrl,
};
